name: Go

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4  
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'  

      - name: Install dependencies
        run: go get .

      - name: Build 
        run: go build -v ./... 

      - name: Test with Go CLI
        run: go test  

      - name: Run GolangCI-Lint (optional)
        uses: golangci/golangci-lint-action@v3 
        with:
          version: 'v1.56.0'  
