on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Go cache
        uses: actions/cache@v3
        with:
          path: ${{ runner.os }}-go
          key: ${{ runner.os }}-go-${{ hashFiles('./go.mod') }}  
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.20 
      
      - name: Run Go tooling (build, test, lint)
        run: |
          make build  
          make test  
          make lint  